### ISSUE TITLE
gitが無いと導入出来ない

### ISSUE THREAD

**Issue by Sayamame-beans** [Sayamame-beans/VRCPhysBone-Relocator#6]
Unity Package Managerの`Add package from git URL...`は、ユーザー側でインストールされたgitを必要とする(組み込まれていない)ため、gitをインストールしていない環境では導入に失敗してしまう。
```
Cannot perform upm operation: Unable to add package [https://github.com/Sayamame-beans/VRCPhysBone-Relocator.git]:
  No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub [NotFound]
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

対応が必要であると考える。
なお、現状でも手動での導入は可能である。

**Comment by Sayamame-beans** [comment]
一時的にunitypackageを作成し、v0.1.0として配布を開始しました。
Packages/以下に生成されるものを別プロジェクトのAssets/以下に移植しただけなので、何か不都合が発生する可能性はありますが…

**Comment by anatawa12** [comment]
VRChat CreatorsCompanionによってgitが導入される模様(ドキュメントでは確認済、未動作確認)なので、問題が無くなる可能性があります

**Comment by Sayamame-beans** [comment]
VCCにて、"Package Maker Tool"というものが使用可能という話を見つけたため、共有します。
詳しくは以下参照。
[vrchat-community/vpm-package-maker: Unity Editor window to help Creators convert their Packages](https://github.com/vrchat-community/vpm-package-maker)
[Converting Assets to a VPM Package | VRChat Creator Companion](https://vcc.docs.vrchat.com/guides/convert-unitypackage/#package-maker-tool)

**Comment by Sayamame-beans** [comment]
VPM community repository、及び[VPAI](https://github.com/anatawa12/VPMPackageAutoInstaller)による導入に対応予定のため、このissueはCloseします。
